version: '3'

services:
  postgresql:
    image: postgres
    container_name: lesson
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=22051996
      - POSTGRES_DATABASE=lesson
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379-6379'